import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { useAuth } from '../hooks/useAuth'
import { nutritionService } from '../services/nutrition-service'
const schema = z.object({ name: z.string().min(2, 'Informe o nome'), brand: z.string().optional(), category: z.string().optional(), base_unit: z.enum(['g','ml']), calories: z.coerce.number().min(0), protein: z.coerce.number().min(0), carbs: z.coerce.number().min(0), fat: z.coerce.number().min(0), fiber: z.coerce.number().min(0), unit_weight_g: z.coerce.number().optional(), portion_weight_g: z.coerce.number().optional() })
type Form = z.infer<typeof schema>
export function AddFood() { const { user } = useAuth(); const qc = useQueryClient(); const { register, handleSubmit, formState: { errors } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { base_unit: 'g', calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 } }); const save = useMutation({ mutationFn: (v: Form) => nutritionService.createFood(user!.id, v), onSuccess: () => qc.invalidateQueries({ queryKey: ['foods'] }) }); return <section className="max-w-3xl"><h1 className="text-2xl font-bold">Cadastrar alimento</h1><p className="mt-1 text-slate-600">Informe os nutrientes por 100 g ou 100 ml.</p><form onSubmit={handleSubmit(v => save.mutate(v))} className="card mt-6 grid gap-4 p-5 md:grid-cols-2"><label>Nome *<input className="field mt-1" {...register('name')}/>{errors.name && <small className="text-rose-600">{errors.name.message}</small>}</label><label>Marca<input className="field mt-1" {...register('brand')}/></label><label>Categoria<input className="field mt-1" placeholder="Ex.: Frutas" {...register('category')}/></label><label>Base nutricional<select className="field mt-1" {...register('base_unit')}><option value="g">100 gramas</option><option value="ml">100 mililitros</option></select></label>{([['calories','Calorias (kcal)'],['protein','Proteínas (g)'],['carbs','Carboidratos (g)'],['fat','Gorduras (g)'],['fiber','Fibras (g)']] as const).map(([key,label]) => <label key={key}>{label}<input className="field mt-1" type="number" step="0.01" {...register(key)}/></label>)}<label>Peso médio da unidade (g)<input className="field mt-1" type="number" step="0.01" {...register('unit_weight_g')}/></label><label>Peso da porção (g)<input className="field mt-1" type="number" step="0.01" {...register('portion_weight_g')}/></label><div className="md:col-span-2"><button className="btn btn-primary" disabled={save.isPending}>{save.isPending ? 'Salvando…' : 'Salvar alimento'}</button>{save.isSuccess && <span className="ml-3 text-sm text-emerald-700">Alimento salvo com sucesso.</span>}{save.error && <span className="ml-3 text-sm text-rose-600">Não foi possível salvar.</span>}</div></form></section> }
