import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
const loginSchema = z.object({ email: z.string().email('Informe um e-mail válido'), password: z.string().min(6, 'Use ao menos 6 caracteres') })
type LoginForm = z.infer<typeof loginSchema>
export function Login({ setup = false }: { setup?: boolean }) { const nav = useNavigate(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<LoginForm>({ resolver: zodResolver(loginSchema) }); const [mode, setMode] = useState<'login'|'signup'|'recover'>('login'); const [message, setMessage] = useState(''); async function submit(v: LoginForm) { if (!supabase) return; const result = mode === 'signup' ? await supabase.auth.signUp({ email: v.email, password: v.password, options: { emailRedirectTo: `${location.origin}/onboarding` } }) : mode === 'recover' ? await supabase.auth.resetPasswordForEmail(v.email, { redirectTo: `${location.origin}/perfil` }) : await supabase.auth.signInWithPassword(v); if (result.error) setMessage(result.error.message); else { setMessage(mode === 'recover' ? 'Enviamos as instruções para seu e-mail.' : 'Tudo certo!'); if (mode === 'login') nav('/') } }
if (setup) return <main className="mx-auto grid min-h-screen max-w-lg place-items-center p-6"><section className="card p-7"><h1 className="text-2xl font-bold text-brand">Configure o NutriPro</h1><p className="mt-3 text-slate-600">Copie <code>.env.example</code> para <code>.env</code> e informe as credenciais públicas do seu projeto Supabase. Nenhuma senha ou chave administrativa é usada no navegador.</p></section></main>
return <main className="grid min-h-screen place-items-center bg-gradient-to-br from-mint to-white p-5"><section className="card w-full max-w-md p-7"><div className="mb-7"><span className="text-2xl font-bold text-brand">NutriPro</span><h1 className="mt-4 text-xl font-bold">{mode === 'login' ? 'Que bom ver você' : mode === 'signup' ? 'Crie sua conta' : 'Recupere sua senha'}</h1></div><form onSubmit={handleSubmit(submit)} className="space-y-4"><label className="block text-sm font-medium">E-mail<input className="field mt-1" type="email" {...register('email')} /></label>{errors.email && <p className="text-sm text-rose-600">{errors.email.message}</p>}{mode !== 'recover' && <label className="block text-sm font-medium">Senha<input className="field mt-1" type="password" {...register('password')} /></label>}{errors.password && <p className="text-sm text-rose-600">{errors.password.message}</p>}{message && <p className="rounded-lg bg-mint p-3 text-sm text-brand">{message}</p>}<button disabled={isSubmitting} className="btn btn-primary w-full">{isSubmitting ? 'Aguarde…' : mode === 'login' ? 'Entrar' : mode === 'signup' ? 'Cadastrar' : 'Enviar instruções'}</button></form><div className="mt-5 flex flex-wrap gap-3 text-sm text-brand"><button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Criar conta' : 'Já tenho conta'}</button><button onClick={() => setMode('recover')}>Esqueci minha senha</button></div></section></main> }
import { useState } from 'react'
export function Onboarding() { const nav = useNavigate(); return <main className="mx-auto max-w-2xl p-5 md:py-12"><section className="card p-6 md:p-8"><h1 className="text-2xl font-bold">Vamos personalizar suas metas</h1><p className="mt-2 text-sm text-slate-600">As estimativas são apenas informativas e não substituem acompanhamento médico ou nutricional.</p><form className="mt-6 grid gap-4 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); nav('/') }}><label>Nome<input required className="field mt-1" /></label><label>Data de nascimento<input type="date" className="field mt-1" /></label><label>Altura (cm)<input type="number" className="field mt-1" /></label><label>Peso atual (kg)<input type="number" className="field mt-1" /></label><label>Objetivo<select className="field mt-1"><option>Emagrecimento</option><option>Manutenção</option><option>Ganho de peso</option></select></label><label>Meta diária de calorias<input defaultValue="2000" type="number" className="field mt-1" /></label><button className="btn btn-primary md:col-span-2">Salvar e começar</button></form></section></main> }
