import { useQuery } from '@tanstack/react-query'
import { Droplets, Plus, Utensils } from 'lucide-react'
import { Link } from 'react-router-dom'
import { MetricCard } from '../components/MetricCard'
import { OfflineStatus } from '../components/OfflineStatus'
import { useAuth } from '../hooks/useAuth'
import { nutritionService } from '../services/nutrition-service'
import { br, sumNutrients } from '../lib/nutrition'
const fallbackGoal = { calories: 2000, protein: 120, carbs: 250, fat: 65, fiber: 30, water_ml: 2500 }
export function Dashboard() { const { user } = useAuth(); const date = new Date().toISOString().slice(0,10); const goals = useQuery({ queryKey: ['goals', user?.id], queryFn: () => nutritionService.goals(user!.id), enabled: !!user }); const items = useQuery({ queryKey: ['items', user?.id, date], queryFn: () => nutritionService.dayItems(user!.id, date), enabled: !!user }); const water = useQuery({ queryKey: ['water', user?.id, date], queryFn: () => nutritionService.water(user!.id, date), enabled: !!user }); const total = sumNutrients(items.data ?? []); const goal = goals.data ?? fallbackGoal; const waterTotal = (water.data ?? []).reduce((n, l) => n + Number(l.amount_ml), 0); return <><header className="flex items-start justify-between"><div><p className="text-slate-500">{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full' }).format(new Date())}</p><h1 className="mt-1 text-2xl font-bold">Olá, cuide de você hoje.</h1></div><OfflineStatus /></header><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><MetricCard label="Calorias" value={total.calories} goal={goal.calories} unit="kcal"/><MetricCard label="Proteínas" value={total.protein} goal={goal.protein} unit="g" color="bg-sky-500"/><MetricCard label="Carboidratos" value={total.carbs} goal={goal.carbs} unit="g" color="bg-amber-500"/><MetricCard label="Gorduras" value={total.fat} goal={goal.fat} unit="g" color="bg-violet-500"/><MetricCard label="Fibras" value={total.fiber} goal={goal.fiber} unit="g" color="bg-lime-600"/><MetricCard label="Água" value={waterTotal} goal={goal.water_ml} unit="ml" color="bg-cyan-500"/></section><section className="mt-7 grid gap-4 md:grid-cols-2"><div className="card p-5"><h2 className="font-bold">Atalhos rápidos</h2><div className="mt-4 flex gap-3"><Link className="btn btn-primary" to="/diario"><Utensils size={17}/> Registrar refeição</Link><Link className="btn btn-soft" to="/adicionar"><Plus size={17}/> Novo alimento</Link></div></div><div className="card p-5"><div className="flex items-center gap-2"><Droplets className="text-cyan-600"/><h2 className="font-bold">Resumo de hoje</h2></div><p className="mt-3 text-sm text-slate-600">Você registrou {items.data?.length ?? 0} alimento(s) e {br(waterTotal)} ml de água.</p><Link className="mt-4 inline-block text-sm font-semibold text-brand" to="/diario">Ver diário →</Link></div></section></> }
