import { useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowDownRight, CalendarDays, ChartNoAxesCombined, CircleGauge, Plus, Target, TrendingDown } from 'lucide-react'

const data = [{ date: '01 jul', weight: 78.4 }, { date: '08 jul', weight: 78.1 }, { date: '15 jul', weight: 77.8 }, { date: '22 jul', weight: 77.6 }, { date: '29 jul', weight: 77.2 }]

export function Evolution() {
  const [range, setRange] = useState('30 dias')
  return <section className="evolution-page"><header className="evolution-header"><div><p className="eyebrow">Sua jornada</p><h1 className="page-title">Veja o quanto você<br/><span>já caminhou.</span></h1><p className="page-subtitle">Acompanhe tendências com calma — resultados consistentes levam tempo.</p></div><button className="btn btn-primary"><Plus size={16}/> Novo registro</button></header>
    <section className="evolution-stats"><article className="evolution-stat stat-current"><span className="evo-stat-icon"><CircleGauge size={17}/></span><p>Peso atual</p><h2>77,2 <small>kg</small></h2><span className="evo-detail"><ArrowDownRight size={13}/> 1,2 kg desde o início</span></article><article className="evolution-stat"><span className="evo-stat-icon evo-icon-start"><CalendarDays size={17}/></span><p>Ponto de partida</p><h2>78,4 <small>kg</small></h2><span className="evo-muted">Registrado em 01 jul</span></article><article className="evolution-stat"><span className="evo-stat-icon evo-icon-goal"><Target size={17}/></span><p>Sua meta</p><h2>70,0 <small>kg</small></h2><span className="evo-muted">Faltam 7,2 kg</span></article></section>
    <article className="weight-chart-card"><div className="chart-heading"><div><p className="eyebrow">Tendência de peso</p><h2>Uma mudança de <span>−1,2 kg</span></h2></div><div className="range-tabs">{['7 dias', '30 dias', '3 meses'].map((item) => <button className={range === item ? 'range-active' : ''} onClick={() => setRange(item)} key={item}>{item}</button>)}</div></div><div className="chart-legend"><span><i/> Peso registrado</span><p><TrendingDown size={14}/> Média em queda</p></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 10, right: 4, left: -25, bottom: 0 }}><defs><linearGradient id="weightFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#73bf99" stopOpacity={.35}/><stop offset="100%" stopColor="#73bf99" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e4ece6" strokeDasharray="3 4"/><XAxis dataKey="date" tickLine={false} axisLine={false} tick={{ fill: '#809089', fontSize: 10 }}/><YAxis domain={['dataMin - 1', 'dataMax + 1']} tickLine={false} axisLine={false} tick={{ fill: '#809089', fontSize: 10 }}/><Tooltip formatter={(value) => [`${value} kg`, 'Peso']} contentStyle={{ border: '1px solid #dce9e0', borderRadius: 12, boxShadow: '0 10px 25px rgba(25,52,37,.12)', fontSize: 12 }}/><Area type="monotone" dataKey="weight" stroke="#33855f" strokeWidth={3} fill="url(#weightFill)" dot={{ r: 4, fill: '#fff', stroke: '#33855f', strokeWidth: 2 }} activeDot={{ r: 5 }}/></AreaChart></ResponsiveContainer></div><footer className="chart-footer"><span><ChartNoAxesCombined size={15}/> Projeção estimada: <strong>76,3 kg em 30 dias</strong></span><p>Baseada na tendência atual.</p></footer></article>
    <section className="evolution-bottom"><article className="measurement-card"><div className="section-title-row"><div><p className="eyebrow">Medidas</p><h2 className="section-heading">Além do número na balança</h2></div><button className="small-outline-btn">Ver todas</button></div><div className="measurement-grid"><div><span>Cintura</span><strong>— <small>cm</small></strong></div><div><span>Quadril</span><strong>— <small>cm</small></strong></div><div><span>% gordura</span><strong>— <small>%</small></strong></div></div><p className="measurement-empty">Registre suas medidas para enxergar outras evoluções.</p></article><article className="evolution-note"><span><TrendingDown size={19}/></span><div><p className="eyebrow">Seu destaque</p><h2>Você está construindo uma tendência positiva.</h2><p>Use essa visão como referência, não como cobrança.</p></div></article></section>
  </section>
}
